# Generated by Django 2.2.4 on 2019-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeabsence',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
