# Generated by Django 2.2.4 on 2019-12-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_auto_20191217_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeabsence',
            name='duration',
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='status',
            field=models.CharField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'UNDER_REVIEW')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='generalabsence',
            name='status',
            field=models.CharField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'UNDER_REVIEW')], default=1, max_length=20),
        ),
    ]
