# Generated by Django 2.2.4 on 2019-12-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absence', '0003_auto_20191218_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeabsence',
            old_name='responded',
            new_name='resubmitted',
        ),
        migrations.RemoveField(
            model_name='employeeabsence',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='employeeabsence',
            name='responded_at',
        ),
        migrations.CreateModel(
            name='EmployeeAbsenceComment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'UNDER_REVIEW')], max_length=20)),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.EmployeeAbsence')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
