# Generated by Django 2.2.4 on 2019-12-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_auto_20191219_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsence',
            name='status',
            field=models.CharField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'IN_REVIEW'), (5, 'WITH_DRAWL')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeabsencecomment',
            name='status',
            field=models.CharField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'IN_REVIEW'), (5, 'WITH_DRAWL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generalabsence',
            name='status',
            field=models.CharField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'IN_REVIEW'), (5, 'WITH_DRAWL')], default=1, max_length=20),
        ),
    ]
