# Generated by Django 2.2.4 on 2019-12-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_auto_20191218_0719'),
        ('absence', '0005_auto_20191220_1222'),
    ]

    operations = [
    ]
