# Generated by Django 2.2.4 on 2019-12-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0006_merge_20191223_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsencecomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
