# Generated by Django 2.2.4 on 2019-12-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0006_merge_20191223_0830'),
        ('absence', '0002_auto_20191223_1049'),
    ]

    operations = [
    ]
