# Generated by Django 2.2.4 on 2019-12-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0007_auto_20191224_0930'),
        ('absence', '0006_merge_20191223_0830'),
    ]

    operations = [
    ]
