# Generated by Django 2.2.4 on 2019-12-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0007_auto_20191224_1222'),
    ]

    operations = [
        migrations.RunSQL("""
        UPDATE absence_employeeabsence set submitted_for_id=absence_employeeabsence.submitted_by_id;
        """)
    ]
