# Generated by Django 2.2.4 on 2019-12-24 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0008_auto_20191224_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsence',
            name='submitted_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL),
        ),
    ]
