# Generated by Django 2.2.4 on 2019-12-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0007_merge_20191224_1031'),
        ('absence', '0008_merge_20191224_1014'),
        ('absence', '0009_auto_20191224_1231'),
    ]

    operations = [
    ]
