# Generated by Django 2.2.4 on 2019-12-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0010_merge_20191227_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalabsence',
            name='department',
            field=models.ManyToManyField(related_name='general_absence_department', to='account.Department'),
        ),
    ]
