# Generated by Django 2.2.4 on 2020-01-05 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0011_auto_20191227_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeabsence',
            name='submitted_on',
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'IN_REVIEW'), (5, 'WITH_DRAWL')], default=1),
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='submitted_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='submitted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
