# Generated by Django 2.2.4 on 2020-01-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0012_auto_20200105_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalabsence',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'IN_REVIEW'), (5, 'WITH_DRAWL')], default=1),
        ),
    ]
