# Generated by Django 2.2.4 on 2020-01-06 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0014_remove_employeeabsence_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsence',
            name='submitted_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
