# Generated by Django 2.2.4 on 2020-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0016_auto_20200107_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeabsence',
            name='submitted_for',
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='created_by_role',
            field=models.CharField(choices=[('manager_admin', 'MANAGER_ADMIN'), ('manager', 'MANAGER'), ('staff', 'STAFF'), ('employee', 'EMPLOYEE')], default='employee', max_length=32),
            preserve_default=False,
        ),
    ]
