# Generated by Django 2.2.4 on 2020-01-07 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absence', '0017_auto_20200107_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeabsence',
            name='created_by_role',
        ),
        migrations.AddField(
            model_name='employeeabsence',
            name='submitted_for',
            field=models.ForeignKey(default='44c2b6a1-635b-4928-8db6-fead083233dd', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_for', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
