# Generated by Django 2.2.4 on 2020-01-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0018_auto_20200107_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeabsence',
            name='resubmitted',
        ),
        migrations.AlterField(
            model_name='employeeabsence',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'IN_REVIEW')], default=1),
        ),
        migrations.AlterField(
            model_name='employeeabsencecomment',
            name='status',
            field=models.CharField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'IN_REVIEW')], max_length=20),
        ),
        migrations.AlterField(
            model_name='generalabsence',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'APPROVED'), (3, 'REJECTED'), (4, 'IN_REVIEW')], default=1),
        ),
    ]
