# Generated by Django 2.2.4 on 2020-04-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0019_auto_20200121_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsencetype',
            name='period',
            field=models.SmallIntegerField(choices=[(1, 'PER_WEEK'), (2, 'PER_MONTH'), (3, 'PER_YEAR'), (4, 'PER_EMPLOYMENT')], default=3),
        ),
    ]
