# Generated by Django 2.2.4 on 2020-04-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0020_auto_20200421_0435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeabsencecomment',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='employeeabsencetype',
            name='hourly',
        ),
        migrations.AddField(
            model_name='employeeabsencetype',
            name='entitlement_type',
            field=models.SmallIntegerField(choices=[(1, 'FULL_DAY'), (2, 'HOURLY'), (3, 'QUITTING')], default=1),
        ),
    ]
