# Generated by Django 2.2.4 on 2020-04-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0021_auto_20200425_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsencetype',
            name='submit_before_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
