# Generated by Django 2.2.4 on 2020-04-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0022_auto_20200427_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeabsence',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='generalabsence',
            options={'ordering': ['-start']},
        ),
        migrations.RenameField(
            model_name='employeeabsence',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='employeeabsence',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='generalabsence',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='generalabsence',
            old_name='start_date',
            new_name='start',
        ),
    ]
