# Generated by Django 2.2.4 on 2020-05-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0023_auto_20200428_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeabsencetype',
            old_name='entitlement_type',
            new_name='duration',
        ),
    ]
