# Generated by Django 2.2.4 on 2020-05-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0024_auto_20200508_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsencetype',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
