# Generated by Django 2.2.4 on 2020-08-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0025_auto_20200512_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeabsence',
            name='body',
        ),
    ]
