# Generated by Django 2.2.4 on 2020-11-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0026_remove_employeeabsence_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsencetype',
            name='period',
            field=models.SmallIntegerField(choices=[(1, 'PER_WEEK'), (2, 'PER_MONTH'), (3, 'PER_YEAR')], default=3),
        ),
    ]
