# Generated by Django 2.2.4 on 2020-12-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0027_auto_20201118_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsencecomment',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeeabsencetype',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='generalabsence',
            name='body',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
