# Generated by Django 2.2.4 on 2020-12-30 06:33

from django.db import migrations
from django.utils.translation import ugettext_lazy as _

from constants.db import ABSENCE_ENTITLEMENT_PERIOD_CHOICE, DURATION


def forwards_func(apps, schema_editor):
    Company = apps.get_model("account", "Company")
    EmployeeAbsenceType = apps.get_model("absence", "EmployeeAbsenceType")

    db_alias = schema_editor.connection.alias
    companies = Company.objects.using(db_alias).all()

    for company in companies:
        EmployeeAbsenceType.objects.using(db_alias).create(
            name=_('ABSENT_FROM_SHIFT'),
            description=_('ABSENT_FROM_SHIFT'),
            entitlement=0,
            period=ABSENCE_ENTITLEMENT_PERIOD_CHOICE.PER_YEAR,
            submit_before_days=0,
            paid=False,
            duration=DURATION.SHIFT,
            company=company
        )


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    EmployeeAbsenceType = apps.get_model("absence", "EmployeeAbsenceType")
    EmployeeAbsenceType.objects.using(db_alias).filter(duration=DURATION.SHIFT).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('absence', '0029_auto_20201209_0532'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
