# Generated by Django 2.2.4 on 2020-12-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0030_auto_20201230_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeabsencetype',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FULL_DAY'), (2, 'HOURLY'), (3, 'QUITTING'), (4, 'SHIFT')], default=1),
        ),
    ]
