# Generated by Django 2.2.4 on 2021-02-01 10:47

import datetime as dt

from django.db import migrations


def adjust_general_absence_end(apps, schema_editor):
    GeneralAbsence = apps.get_model("absence", "GeneralAbsence")

    absences = GeneralAbsence.objects.all()

    for absence in absences:
        absence.end = absence.end + dt.timedelta(days=1)
        absence.save()



## logic for migrating backwards
def reverse_func(apps, schema_editor):
    GeneralAbsence = apps.get_model("absence", "GeneralAbsence")

    absences = GeneralAbsence.objects.all()

    for absence in absences:
        absence.end = absence.end - dt.timedelta(days=1)
        absence.save()


class Migration(migrations.Migration):
    dependencies = [
        ('absence', '0031_auto_20201230_0656'),
    ]

    operations = [
        migrations.RunPython(adjust_general_absence_end, reverse_func)
    ]
