# Generated by Django 2.2.4 on 2019-11-06 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualScheduleReport',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perceived_total_score', models.SmallIntegerField()),
                ('ratio_strongly_preferred_shifts', models.SmallIntegerField()),
                ('ratio_preferred_shifts', models.SmallIntegerField()),
                ('ratio_indifferent_shifts', models.SmallIntegerField()),
                ('ratio_dispreferred_shifts', models.SmallIntegerField()),
                ('ratio_strongly_dispreferred_shifts', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('preferences_deadline', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'ENTERING_DETAILS'), (2, 'COLLECTING_PREFERENCE'), (3, 'PRODUCING_SCHEDULE'), (4, 'REVIEWING_SCHEDULE'), (5, 'PUBLISHED')], default=1)),
                ('manual_input', models.BooleanField(default=False)),
                ('collect_preferences', models.BooleanField(default=True)),
                ('satisfaction_level', models.IntegerField(default=0)),
                ('min_rest_between_shifts_18', models.IntegerField(default=11)),
                ('min_rest_between_shifts_15', models.IntegerField(default=12)),
                ('min_rest_between_shifts_13', models.IntegerField(default=14)),
                ('min_continuous_rest_each_week_18', models.IntegerField(default=35)),
                ('min_continuous_rest_each_week_15', models.IntegerField(default=48)),
                ('min_continuous_rest_each_week_13', models.IntegerField(default=48)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'ENTERING_DETAILS'), (2, 'COLLECTING_PREFERENCE'), (3, 'PRODUCING_SCHEDULE'), (4, 'REVIEWING_SCHEDULE'), (5, 'PUBLISHED')], default=1)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleReport',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleFeedback',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'VERY_UPSET'), (2, 'UPSET'), (3, 'NORMAL'), (4, 'HAPPY'), (5, 'VERY_HAPPY')])),
                ('share_with_manager', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_feedback', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_feedback', to='schedule.Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
