# Generated by Django 2.2.4 on 2019-12-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191106_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
