# Generated by Django 2.2.4 on 2020-02-20 08:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='generic_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
