# Generated by Django 2.2.4 on 2020-06-03 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_generic_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_date',
            new_name='start',
        ),
    ]
