# Generated by Django 2.2.4 on 2020-07-16 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20200603_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulereport',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='min_continuous_rest_each_week_13',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='min_continuous_rest_each_week_15',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='min_continuous_rest_each_week_18',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='min_rest_between_shifts_13',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='min_rest_between_shifts_15',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='min_rest_between_shifts_18',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='satisfaction_level',
        ),
        migrations.DeleteModel(
            name='IndividualScheduleReport',
        ),
        migrations.DeleteModel(
            name='ScheduleReport',
        ),
    ]
